config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  post '/identificacao'      => 'welcome#log_in'
  get '/saida'               => 'welcome#logout', as: :logout

  get '/eventos'             => 'home#index', as: :home
  post '/quests'             => 'quest#create'
  post '/quest_rewards'      => 'quest_reward#create'
  post '/user_rewards'       => 'user_reward#create'

  get '/resgate'             => 'prize#index', as: :prize_index
  post '/arquivar-premio'    => 'prize#archive', as: :archive_prize # for admins
  post '/escolher-premio'    => 'prize#choose', as: :choose_prize

  get '/ranking'             => 'ranking#index', as: :ranking
end

app/models/prize.rb
class Prize < ApplicationRecord
	has_and_belongs_to_many :users

  scope :available, -> { where('quantity > 0') }

  def decrease_quantity!
    self.quantity -= 1
    self.save!
  end
end

app/controllers/prize_controller.rb
class PrizeController < ApplicationController
  before_action :authorize
  before_action :set_prize, only: [:show, :edit, :update, :destroy]

  # GET /prizes
  # GET /prizes.json
  def index
    @prizes = Prize.available
  end

  def choose
    head :bad_request if params[:id].blank?
    prize_id = params[:id]
    prize = Prize.find_by_id(prize_id)

    if prize.present? && prize.quantity > 0 && current_user.choose_prize(prize)
      prize.decrease_quantity!
      flash[:info] = "Parabens!"
      render json: {}
    else
      head :conflict
    end
  end

  # GET /prizes/new
  def new
    @prize = Prize.new
  end

  # POST /prizes
  # POST /prizes.json
  def create
    @prize = Prize.new(prize_params)

    respond_to do |format|
      if @prize.save
        format.html { redirect_to @prize, notice: 'Prize was successfully created.' }
        format.json { render :show, status: :created, location: @prize }
      else
        format.html { render :new }
        format.json { render json: @prize.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prizes/1
  # PATCH/PUT /prizes/1.json
  def update
    respond_to do |format|
      if @prize.update(prize_params)
        format.html { redirect_to @prize, notice: 'Prize was successfully updated.' }
        format.json { render :show, status: :ok, location: @prize }
      else
        format.html { render :edit }
        format.json { render json: @prize.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prizes/1
  # DELETE /prizes/1.json
  def destroy
    @prize.destroy
    respond_to do |format|
      format.html { redirect_to prizes_url, notice: 'Prize was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prize
      @prize = Prize.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prize_params
      params.fetch(:prize, {})
    end

end

app/views/prize/index.html.erb
<div class="row">
  <div class="columns large-12">
      <p id="notice"><%= notice %></p>

      <h2 class="mVBotL">Resgate de pontos</h2>

      <div class="row">
        <% @prizes.each do |prize| %>

          <div class="small-6 medium-4 columns prize">

            <div class="prizeWrapper">
              <div class="prizeImg">
                <%= image_tag('kitkat.png') %>
              </div>
              
              <div class="prizeContent">
                <div class="prizeName">
                  <h4><%= prize.name %></h4>
                </div>           
                
                <div class="prizeCost mVBotL">
                  <span><%= pluralize(prize.cost, "ponto", "pontos") %></span>
                </div>

                <% if user_admin? %>
                <%= link_to 'Arquivar', archive_prize_path, method: :post, class: 'btn filled fullWidth gray', data: { confirm: 'Tem certeza?' } %>
                <% else %>
                <%= link_to 'Eu mereço essa recompensa!', choose_prize_path, method: :post, class: 'btn filled fullWidth green js-choose', data: { confirm: 'Tem certeza?', id: prize.id } %>
                <% end %>
              </div>
            </div>
          </div>

        <% end %>

      </div>

  </div>
</div>