config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  post '/identificacao'      => 'welcome#log_in'
  get '/saida'               => 'welcome#logout', as: :logout

  get '/eventos'             => 'home#index', as: :home
  post '/quests'             => 'quest#create'
  post '/quest_rewards'      => 'quest_reward#create'
  post '/user_rewards'       => 'user_reward#create'

  get '/resgate'             => 'prize#index', as: :prize_index
  post '/arquivar-premio'    => 'prize#archive', as: :archive_prize # for admins
  post '/escolher-premio'    => 'prize#choose', as: :choose_prize

  get '/ranking'             => 'ranking#index', as: :ranking
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prize.rb
class Prize < ApplicationRecord
	has_and_belongs_to_many :users

  scope :available, -> { where('quantity > 0') }

  def decrease_quantity!
    self.quantity -= 1
    self.save!
  end
end

app/models/quest.rb
class Quest < ApplicationRecord
  belongs_to :created_by, class_name: 'User'
  has_many :rewards, class_name: 'QuestReward'

  validates :reward_points, numericality: { only_integer: true, greater_than: 0 }

  def reward_user(rewarded_user)
    if self.created_by.can_give?(self.reward_points)
      QuestReward.create(quest: self, points: self.reward_points, rewarded_user: rewarded_user)
      rewarded_user.increase_points(self.reward_points)
      self.created_by.decrease_points_to_give(self.reward_points)
      self.available = false
      self.save
      true
    end
  end
end

app/models/quest_reward.rb
class QuestReward < ApplicationRecord
  belongs_to :quest
  belongs_to :rewarded_user, class_name: 'User'

  scope :newest_first, -> { order(created_at: :desc) }

  def start_user
    return self.quest.created_by
  end

  def description
    self.quest.description
  end

  def total_points
    self.quest.reward_points
  end
end

app/models/rewarding_user.rb
class RewardingUser < ApplicationRecord
  belongs_to :user
  belongs_to :user_reward

  validates :points, numericality: { only_integer: true, greater_than: 0 }
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_and_belongs_to_many :prizes

  # received_points is the total received since user created
  # available_points are the amount available to exchange for prizes

  # TODO: implementar frozen points

  validates :points_to_give, numericality: { only_integer: true, greater_than: 0 }
  validates :received_points, numericality: { only_integer: true }
  validates :available_points, numericality: { only_integer: true }

  scope :most_rewarded_first, -> { order(received_points: :desc) }

  def increase_points(points)
    self.received_points += points
    self.available_points += points
    self.save!
  end

  def decrease_points_to_give(points)
    self.points_to_give -= points
    self.save!
  end

  def decrease_available_points!(points)
    self.available_points -= points
    self.save!
  end

  def can_give?(points)
    self.points_to_give >= points
  end

  def can_redeem?(points)
    self.available_points >= points
  end

  def first_name
    self.name.to_s[/\A[[:space:]]*(?<first_name>[[:graph:]]+)/, :first_name]
  end

  def last_name
    self.name.to_s[/[[:space:]]+(?<last_name>[[:print:]]*)/, :last_name] || ''
  end

  def at_name
    '@' + name.split(' ').join('.').downcase
  end

  def initials
    unless last_name.blank?
      "#{first_name.first}#{last_name.first}"
    else
      "#{first_name[0..1]}"
    end
  end

  def choose_prize(prize)
    if self.can_redeem?(prize.cost)
      self.prizes << prize
      self.decrease_available_points!(prize.cost)
      true
    end
  end
end

app/models/user_reward.rb
class UserReward < ApplicationRecord
  belongs_to :rewarded_user, class_name: 'User'
  has_many :rewarding_users

  scope :newest_first, -> { order(created_at: :desc) }

  def start_user
    self.rewarding_users.find_by(started: true).user
  end

  def total_points
    self.rewarding_users.pluck(:points).sum
  end

  def self.reward(from:, to:, description:, points:)
    if points > 0 && from.can_give?(points)
      reward = create(description: description, rewarded_user: to)
      from.decrease_points_to_give(points)
      to.increase_points(points)
      RewardingUser.create(user_reward: reward, user: from, points: points, started: true)
      reward
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include TimelineHelper
  # before_action :authorize

  def index

  end
end

app/controllers/prize_controller.rb
class PrizeController < ApplicationController
  before_action :authorize
  before_action :set_prize, only: [:show, :edit, :update, :destroy]

  # GET /prizes
  # GET /prizes.json
  def index
    @prizes = Prize.available
  end

  def choose
    head :bad_request if params[:id].blank?
    prize_id = params[:id]
    prize = Prize.find_by_id(prize_id)

    if prize.present? && prize.quantity > 0 && current_user.choose_prize(prize)
      prize.decrease_quantity!
      flash[:info] = "Parabens!"
      render json: {}
    else
      head :conflict
    end
  end

  # GET /prizes/new
  def new
    @prize = Prize.new
  end

  # POST /prizes
  # POST /prizes.json
  def create
    @prize = Prize.new(prize_params)

    respond_to do |format|
      if @prize.save
        format.html { redirect_to @prize, notice: 'Prize was successfully created.' }
        format.json { render :show, status: :created, location: @prize }
      else
        format.html { render :new }
        format.json { render json: @prize.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prizes/1
  # PATCH/PUT /prizes/1.json
  def update
    respond_to do |format|
      if @prize.update(prize_params)
        format.html { redirect_to @prize, notice: 'Prize was successfully updated.' }
        format.json { render :show, status: :ok, location: @prize }
      else
        format.html { render :edit }
        format.json { render json: @prize.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prizes/1
  # DELETE /prizes/1.json
  def destroy
    @prize.destroy
    respond_to do |format|
      format.html { redirect_to prizes_url, notice: 'Prize was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prize
      @prize = Prize.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prize_params
      params.fetch(:prize, {})
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth0_helper.rb
module Auth0Helper
  private

  # Is the user signed in?
  # @return [Boolean]
  def user_signed_in?
    session[:userinfo].present?
  end

  def client_id
    session[:userinfo].extra.raw_info.clientID
  end

  # Set the @current_user or redirect to public page
  def authenticate_user!
    return
    # Redirect to page that has the login here
    if user_signed_in?
      @current_user = User.find_by(client_id: client_id)
      return if @current_user.present?
    end

    redirect_to login_path if request.path != login_path
  end

  # What's the current_user?
  # @return [Hash]
  def current_user
    @current_user || User.first
  end

  # @return the path to the login page
  def login_path
    root_path
  end

  def user_admin?
    current_user.admin.present?
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def other_users
    User.where.not(id: current_user.id)
  end

  def my_quest
    Quest.find_by(created_by: current_user, available: true)
  end

  def other_quests
    Quest.where.not(created_by: current_user).where(available: true)
  end

  def points_options
    [1, 3, 5]
  end
end

app/helpers/quest_helper.rb
module QuestHelper
end

app/helpers/quest_reward_helper.rb
module QuestRewardHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper

  def timeline
    user_rewards = UserReward.newest_first
    quest_rewards = QuestReward.newest_first
    (user_rewards + quest_rewards).sort_by { |r| r.created_at }.reverse!.take(20)
  end
end

app/helpers/user_helper.rb
module UserHelper
  def user_avatar
  	(image_tag(current_user.image) rescue nil) || current_user.initials
  end

  def avatar_class
  	(user_avatar =~ /img/).present? ? 'user-img' : 'user-initials'
  end
end

app/helpers/user_reward_helper.rb
module UserRewardHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/show.html.erb
<div>
  <img class="avatar" src="<%= @user.image %>"/>
  <h2>Welcome <%= @user.name %></h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Office Heroes" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>

    <!-- fonts typekit -->
    <script src="https://use.typekit.net/gow5cks.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>

  </head>

  <body>
    <header>
      <div class="row align-justify">

        <!-- LOGO -->
        <div class="columns large-3">
          <a class="logo" href="#">
            Office<strong>Heroes</strong>
          </a>
        </div><!-- end columns -->

      <% if current_user.present? %>
        <!-- WALLET & USER -->
        <div class="columns large-9">

          <div class="row align-right align-middle">

            <div class="columns shrink walletWrapper hide-for-small-only">
              <span class="walletPoints">
                <strong><%= current_user.available_points %></strong> pontos
              </span>

              <a class="btn ghost white" href="<%= prize_index_path %>">
                Resgatar
              </a>
            </div><!-- end wallet-wrapper -->

            <div class="columns shrink userAvatar">
              <a class="clearfix" href="#">
                <strong><%= current_user.initials %></strong> <span class="hide-for-small-only"><%= current_user.first_name %></span>
              </a>
            </div>
          </div><!-- end row -->

        </div><!-- end columns -->

      <% end %>
      </div>
    </header>

    <!-- MAIN CONTENT -->
    <main>

      <%= yield %>

    </main>


    <footer>
      <div class="row">
        <div class="columns large-6">
          <span>
            Todos os direitos reservados.
          </span>
        </div>
        <div class="columns large-6">
          <span class="madeWithLove">
            Feito com <i>♥</i> por Morse Code
          </span>
        </div>
      </div>
    </footer>

  </body>
</html>